# render.yaml (només Web Service GRATUÏT)
services:
  - type: web
    name: bot-tg
    env: python
    plan: free
    buildCommand: "pip install -r requirements.txt"
    startCommand: "python bot-tg.py"
    envVars:
      - key: TELEGRAM_BOT_TOKEN
        sync: false
      - key: ALLOWED_CHAT_ID
        sync: false